package com.zydcc.zrdc.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zydcc.zrdc.model.dic.BZGZZDDM;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BZGZZDDM".
*/
public class BZGZZDDMDao extends AbstractDao<BZGZZDDM, Void> {

    public static final String TABLENAME = "BZGZZDDM";

    /**
     * Properties of entity BZGZZDDM.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property DM = new Property(0, String.class, "DM", false, "DM");
        public final static Property ID = new Property(1, String.class, "ID", false, "ID");
        public final static Property MC = new Property(2, String.class, "MC", false, "MC");
    }


    public BZGZZDDMDao(DaoConfig config) {
        super(config);
    }
    
    public BZGZZDDMDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BZGZZDDM entity) {
        stmt.clearBindings();
 
        String DM = entity.getDM();
        if (DM != null) {
            stmt.bindString(1, DM);
        }
 
        String ID = entity.getID();
        if (ID != null) {
            stmt.bindString(2, ID);
        }
 
        String MC = entity.getMC();
        if (MC != null) {
            stmt.bindString(3, MC);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BZGZZDDM entity) {
        stmt.clearBindings();
 
        String DM = entity.getDM();
        if (DM != null) {
            stmt.bindString(1, DM);
        }
 
        String ID = entity.getID();
        if (ID != null) {
            stmt.bindString(2, ID);
        }
 
        String MC = entity.getMC();
        if (MC != null) {
            stmt.bindString(3, MC);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public BZGZZDDM readEntity(Cursor cursor, int offset) {
        BZGZZDDM entity = new BZGZZDDM( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // DM
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // MC
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BZGZZDDM entity, int offset) {
        entity.setDM(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMC(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(BZGZZDDM entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(BZGZZDDM entity) {
        return null;
    }

    @Override
    public boolean hasKey(BZGZZDDM entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
