package com.zydcc.zrdc.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zydcc.zrdc.model.dic.DLTB;
import com.zydcc.zrdc.model.bean.Layer;
import com.zydcc.zrdc.model.dic.BSLXDM;
import com.zydcc.zrdc.model.dic.BZGZZDDM;
import com.zydcc.zrdc.model.dic.BZLXDM;

import com.zydcc.zrdc.greendao.DLTBDao;
import com.zydcc.zrdc.greendao.LayerDao;
import com.zydcc.zrdc.greendao.BSLXDMDao;
import com.zydcc.zrdc.greendao.BZGZZDDMDao;
import com.zydcc.zrdc.greendao.BZLXDMDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dLTBDaoConfig;
    private final DaoConfig layerDaoConfig;
    private final DaoConfig bSLXDMDaoConfig;
    private final DaoConfig bZGZZDDMDaoConfig;
    private final DaoConfig bZLXDMDaoConfig;

    private final DLTBDao dLTBDao;
    private final LayerDao layerDao;
    private final BSLXDMDao bSLXDMDao;
    private final BZGZZDDMDao bZGZZDDMDao;
    private final BZLXDMDao bZLXDMDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dLTBDaoConfig = daoConfigMap.get(DLTBDao.class).clone();
        dLTBDaoConfig.initIdentityScope(type);

        layerDaoConfig = daoConfigMap.get(LayerDao.class).clone();
        layerDaoConfig.initIdentityScope(type);

        bSLXDMDaoConfig = daoConfigMap.get(BSLXDMDao.class).clone();
        bSLXDMDaoConfig.initIdentityScope(type);

        bZGZZDDMDaoConfig = daoConfigMap.get(BZGZZDDMDao.class).clone();
        bZGZZDDMDaoConfig.initIdentityScope(type);

        bZLXDMDaoConfig = daoConfigMap.get(BZLXDMDao.class).clone();
        bZLXDMDaoConfig.initIdentityScope(type);

        dLTBDao = new DLTBDao(dLTBDaoConfig, this);
        layerDao = new LayerDao(layerDaoConfig, this);
        bSLXDMDao = new BSLXDMDao(bSLXDMDaoConfig, this);
        bZGZZDDMDao = new BZGZZDDMDao(bZGZZDDMDaoConfig, this);
        bZLXDMDao = new BZLXDMDao(bZLXDMDaoConfig, this);

        registerDao(DLTB.class, dLTBDao);
        registerDao(Layer.class, layerDao);
        registerDao(BSLXDM.class, bSLXDMDao);
        registerDao(BZGZZDDM.class, bZGZZDDMDao);
        registerDao(BZLXDM.class, bZLXDMDao);
    }
    
    public void clear() {
        dLTBDaoConfig.clearIdentityScope();
        layerDaoConfig.clearIdentityScope();
        bSLXDMDaoConfig.clearIdentityScope();
        bZGZZDDMDaoConfig.clearIdentityScope();
        bZLXDMDaoConfig.clearIdentityScope();
    }

    public DLTBDao getDLTBDao() {
        return dLTBDao;
    }

    public LayerDao getLayerDao() {
        return layerDao;
    }

    public BSLXDMDao getBSLXDMDao() {
        return bSLXDMDao;
    }

    public BZGZZDDMDao getBZGZZDDMDao() {
        return bZGZZDDMDao;
    }

    public BZLXDMDao getBZLXDMDao() {
        return bZLXDMDao;
    }

}
